name: "dbt_case_study"
version: "1.0"
profile: "snowflake" # assuming you have your Snowflake profile configured

config-version: 2

# Model configurations
models:
  dbt_case_study:
    # Customer Master Model configuration
    customer_master:
      materialized: view
      schema: public
    # Product Master Model configuration
    product_master:
      materialized: view
      schema: public
    # Day Invoice Model configuration (incremental model)
    day_invoice:
      materialized: incremental
      incremental_strategy: append
      unique_key: transaction_date
      schema: public
    # Month Invoice Model configuration (table)
    month_invoice:
      materialized: table
      schema: public
    # Default model settings
    +enabled: true
    +persist_docs:
      columns: true
    +tags:
      - core

# Seed configuration for country_code.csv
seeds:
  dbt_case_study:
    country_code:
      file: data/country_code.csv
      header: true
      delimiter: ","
      quote: '"'


# # Target configurations
# target:
#   name: dev
#   type: snowflake
#   threads: 4
#   database: YOUR_DATABASE
#   warehouse: YOUR_WAREHOUSE
#   role: YOUR_ROLE
#   schema: public
#   account: YOUR_ACCOUNT
