version: 2

sources:
  - name: stage_cust_mstr_kna1
    database: dbt_case_study
    schema: public
    tables:
      - name: stage_cust_mstr_kna1

  - name: stage_cust_mstr_tkna1
    database: dbt_case_study
    schema: public
    tables:
      - name: stage_cust_mstr_tkna1

  - name: stage_prod_mstr_pna1
    database: dbt_case_study
    schema: public
    tables:
      - name: stage_prod_mstr_pna1

  - name: stage_prod_mstr_tpna1
    database: dbt_case_study
    schema: public
    tables:
      - name: stage_prod_mstr_tpna1

  - name: stage_invoice_raw
    database: dbt_case_study
    schema: public
    tables:
      - name: stage_invoice_raw
