version: 2

sources:
  - name: stage
    database: Testing
    schema: PUBLIC
    tables:
      - name: STAGE_CUST_MSTR_KNA1
        description: "Customer master data from KNA1"
      - name: STAGE_CUST_MSTR_TKNA1
        description: "Customer master data from TKNA1"
      - name: STAGE_PROD_MSTR_PNA1
        description: "Product master data from PNA1"
      - name: STAGE_PROD_MSTR_TPNA1
        description: "Product master data from TPNA1"
      - name: STAGE_INVOICE_RAW
        description: "Raw transactional invoice data"